### PR TITLE
Update GH workflow

### PR DESCRIPTION
**Pull request by jtmilan**
Update GH workflow

### CODE REVIEW

**Comment by jtmilan** [comment]
> #### Terraform Format and Style 🖌`success`
> #### Terraform Initialization ⚙️`success`
> #### Terraform Validation 🤖
> Warning: Quoted references are deprecated
> 
> on .terraform/modules/vpc.subnets/private.tf line 45, in resource "aws_subnet" "private":
> 45: ignore_changes = ["tags.kubernetes", "tags.SubnetType"]
> 
> In this context, references are expected literally rather than in quotes.
> Terraform 0.11 and earlier required quotes, but quoted references are now
> deprecated and will be removed in a future version of Terraform. Remove the
> quotes surrounding this reference to silence this warning.
> 
> (and 3 more similar warnings elsewhere)
> 
> Success! The configuration is valid, but there were some validation warnings as shown above.
> 
> #### Terraform Plan 📖`success`
> Show Plan
> ```terraform
> Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
> will stop streaming the logs, but will not stop the plan running remotely.
> 
> Preparing the remote plan...
> 
> To view this run in a browser, visit:
> https://app.terraform.io/app/milan/development/runs/run-rU1sp8MYN9qkwDvS
> 
> Waiting for the plan to start...
> 
> Terraform v0.12.29
> Configuring remote state backend...
> Initializing Terraform configuration...
> 2020/08/27 07:29:17 [DEBUG] Using modified User-Agent: Terraform/0.12.29 TFC/5aa588c70f
> Refreshing Terraform state in-memory prior to plan...
> The refreshed state will be used to calculate this plan, but will not be
> persisted to local or remote state storage.
> 
> module.vpc.module.subnets.module.label.data.null_data_source.tags_as_list_of_maps[2]: Refreshing state...
> module.vpc.module.subnets.module.private_label.data.null_data_source.tags_as_list_of_maps[3]: Refreshing state...
> module.vpc.module.subnets.module.private_label.data.null_data_source.tags_as_list_of_maps[4]: Refreshing state...
> module.vpc.module.subnets.module.label.data.null_data_source.tags_as_list_of_maps[0]: Refreshing state...
> module.vpc.module.subnets.module.label.data.null_data_source.tags_as_list_of_maps[1]: Refreshing state...
> module.vpc.module.subnets.module.private_label.data.null_data_source.tags_as_list_of_maps[0]: Refreshing state...
> module.vpc.module.subnets.module.private_label.data.null_data_source.tags_as_list_of_maps[1]: Refreshing state...
> module.vpc.module.subnets.module.nat_instance_label.data.null_data_source.tags_as_list_of_maps[0]: Refreshing state...
> module.vpc.module.subnets.module.private_label.data.null_data_source.tags_as_list_of_maps[2]: Refreshing state...
> module.vpc.module.subnets.module.nat_label.data.null_data_source.tags_as_list_of_maps[0]: Refreshing state...
> module.vpc.module.subnets.module.nat_instance_label.data.null_data_source.tags_as_list_of_maps[3]: Refreshing state...
> module.vpc.module.subnets.module.nat_label.data.null_data_source.tags_as_list_of_maps[3]: Refreshing state...
> module.vpc.module.subnets.module.nat_label.data.null_data_source.tags_as_list_of_maps[1]: Refreshing state...
> module.vpc.module.subnets.module.nat_instance_label.data.null_data_source.tags_as_list_of_maps[2]: Refreshing state...
> module.vpc.module.subnets.module.nat_label.data.null_data_source.tags_as_list_of_maps[2]: Refreshing state...
> module.vpc.module.subnets.module.public_label.data.null_data_source.tags_as_list_of_maps[0]: Refreshing state...
> module.vpc.module.subnets.module.public_label.data.null_data_source.tags_as_list_of_maps[1]: Refreshing state...
> module.vpc.module.subnets.module.nat_instance_label.data.null_data_source.tags_as_list_of_maps[1]: Refreshing state...
> module.vpc.module.subnets.module.public_label.data.null_data_source.tags_as_list_of_maps[2]: Refreshing state...
> module.vpc.module.subnets.module.public_label.data.null_data_source.tags_as_list_of_maps[3]: Refreshing state...
> module.vpc.module.subnets.module.public_label.data.null_data_source.tags_as_list_of_maps[4]: Refreshing state...
> module.vpc.module.subnets.data.aws_availability_zones.available: Refreshing state...
> 
> ------------------------------------------------------------------------
> 
> An execution plan has been generated and is shown below.
> Resource actions are indicated with the following symbols:
>   + create
>  <= read (data resources)
> 
> Terraform will perform the following actions:
> 
>   # module.vpc.module.subnets.data.aws_vpc.default will be read during apply
>   # (config refers to values not yet known)
>  <= data "aws_vpc" "default"  {
>       + arn                     = (known after apply)
>       + cidr_block              = (known after apply)
>       + cidr_block_associations = (known after apply)
>       + default                 = (known after apply)
>       + dhcp_options_id         = (known after apply)
>       + enable_dns_hostnames    = (known after apply)
>       + enable_dns_support      = (known after apply)
>       + id                      = (known after apply)
>       + instance_tenancy        = (known after apply)
>       + ipv6_association_id     = (known after apply)
>       + ipv6_cidr_block         = (known after apply)
>       + main_route_table_id     = (known after apply)
>       + owner_id                = (known after apply)
>       + state                   = (known after apply)
>       + tags                    = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_network_acl.private[0] will be created
>   + resource "aws_network_acl" "private" {
>       + egress     = [
>           + {
>               + action          = "allow"
>               + cidr_block      = "0.0.0.0/0"
>               + from_port       = 0
>               + icmp_code       = null
>               + icmp_type       = null
>               + ipv6_cidr_block = ""
>               + protocol        = "-1"
>               + rule_no         = 100
>               + to_port         = 0
>             },
>         ]
>       + id         = (known after apply)
>       + ingress    = [
>           + {
>               + action          = "allow"
>               + cidr_block      = "0.0.0.0/0"
>               + from_port       = 0
>               + icmp_code       = null
>               + icmp_type       = null
>               + ipv6_cidr_block = ""
>               + protocol        = "-1"
>               + rule_no         = 100
>               + to_port         = 0
>             },
>         ]
>       + owner_id   = (known after apply)
>       + subnet_ids = (known after apply)
>       + tags       = {
>           + "Attributes"          = "private"
>           + "Name"                = "eks-cluster-development-vpc"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "private"
>         }
>       + vpc_id     = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_network_acl.public[0] will be created
>   + resource "aws_network_acl" "public" {
>       + egress     = [
>           + {
>               + action          = "allow"
>               + cidr_block      = "0.0.0.0/0"
>               + from_port       = 0
>               + icmp_code       = null
>               + icmp_type       = null
>               + ipv6_cidr_block = ""
>               + protocol        = "-1"
>               + rule_no         = 100
>               + to_port         = 0
>             },
>         ]
>       + id         = (known after apply)
>       + ingress    = [
>           + {
>               + action          = "allow"
>               + cidr_block      = "0.0.0.0/0"
>               + from_port       = 0
>               + icmp_code       = null
>               + icmp_type       = null
>               + ipv6_cidr_block = ""
>               + protocol        = "-1"
>               + rule_no         = 100
>               + to_port         = 0
>             },
>         ]
>       + owner_id   = (known after apply)
>       + subnet_ids = (known after apply)
>       + tags       = {
>           + "Attributes"          = "public"
>           + "Name"                = "eks-cluster-development-vpc"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "public"
>         }
>       + vpc_id     = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route.public[0] will be created
>   + resource "aws_route" "public" {
>       + destination_cidr_block     = "0.0.0.0/0"
>       + destination_prefix_list_id = (known after apply)
>       + egress_only_gateway_id     = (known after apply)
>       + gateway_id                 = (known after apply)
>       + id                         = (known after apply)
>       + instance_id                = (known after apply)
>       + instance_owner_id          = (known after apply)
>       + nat_gateway_id             = (known after apply)
>       + network_interface_id       = (known after apply)
>       + origin                     = (known after apply)
>       + route_table_id             = (known after apply)
>       + state                      = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table.private[0] will be created
>   + resource "aws_route_table" "private" {
>       + id               = (known after apply)
>       + owner_id         = (known after apply)
>       + propagating_vgws = (known after apply)
>       + route            = (known after apply)
>       + tags             = {
>           + "Attributes"          = "private"
>           + "Name"                = "eks-cluster-development-vpc-private-us-west-2a"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "private"
>         }
>       + vpc_id           = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table.private[1] will be created
>   + resource "aws_route_table" "private" {
>       + id               = (known after apply)
>       + owner_id         = (known after apply)
>       + propagating_vgws = (known after apply)
>       + route            = (known after apply)
>       + tags             = {
>           + "Attributes"          = "private"
>           + "Name"                = "eks-cluster-development-vpc-private-us-west-2b"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "private"
>         }
>       + vpc_id           = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table.private[2] will be created
>   + resource "aws_route_table" "private" {
>       + id               = (known after apply)
>       + owner_id         = (known after apply)
>       + propagating_vgws = (known after apply)
>       + route            = (known after apply)
>       + tags             = {
>           + "Attributes"          = "private"
>           + "Name"                = "eks-cluster-development-vpc-private-us-west-2c"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "private"
>         }
>       + vpc_id           = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table.public[0] will be created
>   + resource "aws_route_table" "public" {
>       + id               = (known after apply)
>       + owner_id         = (known after apply)
>       + propagating_vgws = (known after apply)
>       + route            = (known after apply)
>       + tags             = {
>           + "Attributes"          = "public"
>           + "Name"                = "eks-cluster-development-vpc"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "public"
>         }
>       + vpc_id           = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table_association.private[0] will be created
>   + resource "aws_route_table_association" "private" {
>       + id             = (known after apply)
>       + route_table_id = (known after apply)
>       + subnet_id      = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table_association.private[1] will be created
>   + resource "aws_route_table_association" "private" {
>       + id             = (known after apply)
>       + route_table_id = (known after apply)
>       + subnet_id      = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table_association.private[2] will be created
>   + resource "aws_route_table_association" "private" {
>       + id             = (known after apply)
>       + route_table_id = (known after apply)
>       + subnet_id      = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table_association.public[0] will be created
>   + resource "aws_route_table_association" "public" {
>       + id             = (known after apply)
>       + route_table_id = (known after apply)
>       + subnet_id      = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table_association.public[1] will be created
>   + resource "aws_route_table_association" "public" {
>       + id             = (known after apply)
>       + route_table_id = (known after apply)
>       + subnet_id      = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_route_table_association.public[2] will be created
>   + resource "aws_route_table_association" "public" {
>       + id             = (known after apply)
>       + route_table_id = (known after apply)
>       + subnet_id      = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_subnet.private[0] will be created
>   + resource "aws_subnet" "private" {
>       + arn                             = (known after apply)
>       + assign_ipv6_address_on_creation = false
>       + availability_zone               = "us-west-2a"
>       + availability_zone_id            = (known after apply)
>       + cidr_block                      = "172.16.0.0/19"
>       + id                              = (known after apply)
>       + ipv6_cidr_block                 = (known after apply)
>       + ipv6_cidr_block_association_id  = (known after apply)
>       + map_public_ip_on_launch         = false
>       + owner_id                        = (known after apply)
>       + tags                            = {
>           + "Attributes"          = "private"
>           + "Name"                = "eks-cluster-development-vpc-private-us-west-2a"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "private"
>         }
>       + vpc_id                          = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_subnet.private[1] will be created
>   + resource "aws_subnet" "private" {
>       + arn                             = (known after apply)
>       + assign_ipv6_address_on_creation = false
>       + availability_zone               = "us-west-2b"
>       + availability_zone_id            = (known after apply)
>       + cidr_block                      = "172.16.32.0/19"
>       + id                              = (known after apply)
>       + ipv6_cidr_block                 = (known after apply)
>       + ipv6_cidr_block_association_id  = (known after apply)
>       + map_public_ip_on_launch         = false
>       + owner_id                        = (known after apply)
>       + tags                            = {
>           + "Attributes"          = "private"
>           + "Name"                = "eks-cluster-development-vpc-private-us-west-2b"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "private"
>         }
>       + vpc_id                          = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_subnet.private[2] will be created
>   + resource "aws_subnet" "private" {
>       + arn                             = (known after apply)
>       + assign_ipv6_address_on_creation = false
>       + availability_zone               = "us-west-2c"
>       + availability_zone_id            = (known after apply)
>       + cidr_block                      = "172.16.64.0/19"
>       + id                              = (known after apply)
>       + ipv6_cidr_block                 = (known after apply)
>       + ipv6_cidr_block_association_id  = (known after apply)
>       + map_public_ip_on_launch         = false
>       + owner_id                        = (known after apply)
>       + tags                            = {
>           + "Attributes"          = "private"
>           + "Name"                = "eks-cluster-development-vpc-private-us-west-2c"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "private"
>         }
>       + vpc_id                          = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_subnet.public[0] will be created
>   + resource "aws_subnet" "public" {
>       + arn                             = (known after apply)
>       + assign_ipv6_address_on_creation = false
>       + availability_zone               = "us-west-2a"
>       + availability_zone_id            = (known after apply)
>       + cidr_block                      = "172.16.128.0/19"
>       + id                              = (known after apply)
>       + ipv6_cidr_block                 = (known after apply)
>       + ipv6_cidr_block_association_id  = (known after apply)
>       + map_public_ip_on_launch         = true
>       + owner_id                        = (known after apply)
>       + tags                            = {
>           + "Attributes"          = "public"
>           + "Name"                = "eks-cluster-development-vpc-public-us-west-2a"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "public"
>         }
>       + vpc_id                          = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_subnet.public[1] will be created
>   + resource "aws_subnet" "public" {
>       + arn                             = (known after apply)
>       + assign_ipv6_address_on_creation = false
>       + availability_zone               = "us-west-2b"
>       + availability_zone_id            = (known after apply)
>       + cidr_block                      = "172.16.160.0/19"
>       + id                              = (known after apply)
>       + ipv6_cidr_block                 = (known after apply)
>       + ipv6_cidr_block_association_id  = (known after apply)
>       + map_public_ip_on_launch         = true
>       + owner_id                        = (known after apply)
>       + tags                            = {
>           + "Attributes"          = "public"
>           + "Name"                = "eks-cluster-development-vpc-public-us-west-2b"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "public"
>         }
>       + vpc_id                          = (known after apply)
>     }
> 
>   # module.vpc.module.subnets.aws_subnet.public[2] will be created
>   + resource "aws_subnet" "public" {
>       + arn                             = (known after apply)
>       + assign_ipv6_address_on_creation = false
>       + availability_zone               = "us-west-2c"
>       + availability_zone_id            = (known after apply)
>       + cidr_block                      = "172.16.192.0/19"
>       + id                              = (known after apply)
>       + ipv6_cidr_block                 = (known after apply)
>       + ipv6_cidr_block_association_id  = (known after apply)
>       + map_public_ip_on_launch         = true
>       + owner_id                        = (known after apply)
>       + tags                            = {
>           + "Attributes"          = "public"
>           + "Name"                = "eks-cluster-development-vpc-public-us-west-2c"
>           + "Namespace"           = "eks-cluster"
>           + "Stage"               = "development"
>           + "cpco.io/subnet/type" = "public"
>         }
>       + vpc_id                          = (known after apply)
>     }
> 
>   # module.vpc.module.vpc.aws_default_security_group.default[0] will be created
>   + resource "aws_default_security_group" "default" {
>       + arn                    = (known after apply)
>       + egress                 = []
>       + id                     = (known after apply)
>       + ingress                = []
>       + name                   = (known after apply)
>       + owner_id               = (known after apply)
>       + revoke_rules_on_delete = false
>       + tags                   = {
>           + "Name"      = "Default Security Group"
>           + "Namespace" = "eks-cluster"
>           + "Stage"     = "development"
>         }
>       + vpc_id                 = (known after apply)
>     }
> 
>   # module.vpc.module.vpc.aws_internet_gateway.default[0] will be created
>   + resource "aws_internet_gateway" "default" {
>       + id       = (known after apply)
>       + owner_id = (known after apply)
>       + tags     = {
>           + "Name"      = "eks-cluster-development-vpc"
>           + "Namespace" = "eks-cluster"
>           + "Stage"     = "development"
>         }
>       + vpc_id   = (known after apply)
>     }
> 
>   # module.vpc.module.vpc.aws_vpc.default[0] will be created
>   + resource "aws_vpc" "default" {
>       + arn                              = (known after apply)
>       + assign_generated_ipv6_cidr_block = true
>       + cidr_block                       = "172.16.0.0/16"
>       + default_network_acl_id           = (known after apply)
>       + default_route_table_id           = (known after apply)
>       + default_security_group_id        = (known after apply)
>       + dhcp_options_id                  = (known after apply)
>       + enable_classiclink               = false
>       + enable_classiclink_dns_support   = false
>       + enable_dns_hostnames             = true
>       + enable_dns_support               = true
>       + id                               = (known after apply)
>       + instance_tenancy                 = "default"
>       + ipv6_association_id              = (known after apply)
>       + ipv6_cidr_block                  = (known after apply)
>       + main_route_table_id              = (known after apply)
>       + owner_id                         = (known after apply)
>       + tags                             = {
>           + "Name"      = "eks-cluster-development-vpc"
>           + "Namespace" = "eks-cluster"
>           + "Stage"     = "development"
>         }
>     }
> 
> Plan: 22 to add, 0 to change, 0 to destroy.
> 
> Warning: Quoted references are deprecated
> 
>   on .terraform/modules/vpc.subnets/private.tf line 45, in resource "aws_subnet" "private":
>   45:     ignore_changes = ["tags.kubernetes", "tags.SubnetType"]
> 
> In this context, references are expected literally rather than in quotes.
> Terraform 0.11 and earlier required quotes, but quoted references are now
> deprecated and will be removed in a future version of Terraform. Remove the
> quotes surrounding this reference to silence this warning.
> 
> (and 3 more similar warnings elsewhere)
> ```
> 
> _Pusher: @jtmilan, Action: `pull_request`, Working Directory: `.`, Workflow: `Infra Development CI/CD Workflow`_

terraform validate

**Comment by jtmilan** [comment]
terraform validate

**Comment by jtmilan** [comment]
terraform apply

**Comment by jtmilan** [comment]
terraform apply

**Comment by jtmilan** [comment]
terraform apply

**Comment by jtmilan** [comment]
terraform apply development

**Comment by milantechlive** [comment]
terraform apply development

**Pull request merged**
